### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by dufferzafar** [gediminasz/ctags-companion#11]
The extension isn't working. When i select the reindex command. The status bar shows `Ctags Companion: reindexing <project name>` but nothing actually happens.

Go to symbol in file, Go to symbol in Workspace, Go to definition, nothing works!

How can I debug this further?

```
╰─❯ ctags --version
Universal Ctags 0.0.0(bf00708d), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  2 2019, 16:28:04
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +yaml, +packcc
```

**Comment by gediminasz** [comment]
Hello @dufferzafar . Is the `.vscode/.tags` file present?

I know this is confusing but are you using the "reindex" *command* or the "rebuild ctags" *task*? 

### Reindex

This only reindexes an existing ctags file. So if it is not present, nothing gets indexed.

<img width="616" alt="Screenshot 2021-02-16 at 11 20 38" src="https://user-images.githubusercontent.com/699568/108042862-0bedf600-7049-11eb-9c70-8bdb0fa19e9e.png">

### Rebuild

This will generate the ctags file and index it.

<img width="610" alt="Screenshot 2021-02-16 at 11 23 07" src="https://user-images.githubusercontent.com/699568/108043140-66875200-7049-11eb-9188-543b8d6ba302.png">

<img width="614" alt="Screenshot 2021-02-16 at 11 20 05" src="https://user-images.githubusercontent.com/699568/108042774-ee209100-7048-11eb-9718-03116a822a59.png">
