### ISSUE TITLE
there is a bug when .tags file contains "hasOwnProperty" or other built in object property names

### ISSUE THREAD

**Issue by ocoka** [gediminasz/ctags-companion#15]
here 
https://github.com/gediminasz/ctags-companion/blob/master/src/index.js#L47
steps to reproduce:
create new js project
somethere in code define hasOwnProperty as method
index project

**Comment by gediminasz** [comment]
Thanks for the report!

I will try and reproduce the issue but I think I can fix this using `Map` instead of a plain old object.

**Comment by ocoka** [comment]
Hi, 

> I will try and reproduce the issue but I think I can fix this using `Map` instead of a plain old object.

Indeed, i think that will be the fastest way to fix

**Comment by ocoka** [comment]
And I've missed the line where the bug occurs, here
https://github.com/gediminasz/ctags-companion/blob/master/src/index.js#L47
also edited in my comment above
thx, for you time and work

**Comment by gediminasz** [comment]
I have just published a new version to vscode marketplace. Let me know if the issue persists.

**Comment by ocoka** [comment]
thx. it works now
