### ISSUE TITLE
Error: the task 'Ctags Companion: rebuild ctags' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:

### ISSUE THREAD

**Issue by yoe3eyes** [gediminasz/ctags-companion#19]
Hi, when I try to use ctags-companion in SystemVerilog project, found the error below.
My vscode version is 1.52.1 which is released in 2020-12-16. Is the version incompatible？ 

> Error: the task 'Ctags Companion: rebuild ctags' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
> {
>     "type": "shell",
>     "id": "shell,ctags -R --fields=+nKz -f .vscode/.tags,",
>     "problemMatcher": [],
>     "label": "Ctags Companion: rebuild ctags"
> }

Many thanks to your help.

**Comment by gediminasz** [comment]
Hello, thank you for the bug report. I will look into it.

For now you may try this workaround:

1. manually run `ctags -R --fields=+nKz -f .vscode/.tags` from command line
2. invoke "reindex" command from vscode

<img width="618" alt="Screenshot 2022-01-26 at 12 36 59" src="https://user-images.githubusercontent.com/699568/151148297-d7731d7a-9673-4309-b999-c18b77bfeb7f.png">

**Comment by gediminasz** [comment]
@yoe3eyes I downloaded vscode 1.52.1 but I am unable to reproduce the issue.

Which Ctags Companion version do you have installed?

**Comment by yoe3eyes** [comment]
I've tried the "reindex" command manually under x64 and Linux, both of them can't find the command.

But, under x64 which I installed the newest version of all the tools, the “rebuild ctags” works fine and I can use the Go to Defintion now. Thank you for the work~

I think it might be my Linux environment is separated from the internet which I can only use FTP to upload extension.If it is so, is there any thing I can do to use the extension without internet？

**Comment by yoe3eyes** [comment]
Hi, the problem seems have been solved when I update the universal-ctags to the newest. I can use "Go to Defintion" now after rebuild. (Or it could be I organized filelist in a right way, I'm not sure which action made it work).

And the question mentioned above seem not fix yet. I can still see the error report.
Anyway, Its very helpful. Thank you for your reply~
