### ISSUE TITLE
how to clear symbol index

### ISSUE THREAD

**Issue by Johnmc104** [gediminasz/ctags-companion#23]
i used "history" extension, Many useless file indexes are generated. when i del these file, and rebuild ctags file,  the symbol index remains unchanged.

**Comment by Johnmc104** [comment]
i find it，del vscode cache file at
C:\Users\<username>\AppData\Roaming\Code\User\workspaceStorage

Whether this process can be completed automatically when ctags file is generated

**Comment by gediminasz** [comment]
@Johnmc104 Could you share a link to the "history" extension you mention? I will try to reproduce your problem.

Do you build the ctags file using some external process or the "Ctags Companion: rebuild ctags" task via `Terminal > Run Task`?

**Comment by Johnmc104** [comment]
at [here](https://marketplace.visualstudio.com/items?itemName=xyz.local-history)

**Comment by gediminasz** [comment]
@Johnmc104 Could you try adding the following to your vscode config?

```
"ctags-companion.command": "ctags -R --fields=+nKz -f .vscode/.tags --exclude=.history"
```

Would that solve your issue?

**Comment by gediminasz** [comment]
@Johnmc104 is this issue still relevant? Were you able to solve your problem?
