### ISSUE TITLE
Ctags-companion does not work for Linux kernel source code.

### ISSUE THREAD

**Issue by Aningsk** [gediminasz/ctags-companion#24]
I use Ctags-companion in VScode, and it is perfect for my project source code.
But it cannot work in Linux source code (linux-5.15.30): when I try "cmd + click" on some Linux function, VScode does not jump to the function define.
I also try "Terminal > Run Task... and select 'Ctags Companion: rebuild ctags'", it's not working too.
However, I copy tags file, and using it with Vim, it can jump to the define. Such as:
```
cd linux-5.15.30/
cp .vscode/.tags ./tags
vim <some_linux_c_file>
# And I can goto the function define by "Ctrl + ]" in Vim.
```

Is there any suggestion about Ctags-companion with Linux source code ?

**Comment by gediminasz** [comment]
I assume you are talking about this repository: https://github.com/torvalds/linux. It looks like the extension can't handle a repository of this size.

I will look into more efficient ways to look up tags, e.g. using `readtags`.

Thank you for bringing this up!

**Comment by Aningsk** [comment]
Thanks for your reply.
Yes, it is the repository. The Linux kernel is pretty large and I notice the tags file(.vscode/.tags) is near 700MB.

**Comment by gediminasz** [comment]
@Aningsk I have pushed a new version of the extension (2023.1.0). If it is still relevant for you, could you try it out?

Please also add this setting in your settings JSON file:

```
"ctags-companion.readtagsEnabled": true
```

**Comment by Aningsk** [comment]
I had tried the new version (2023.1.0) with setting `readtagsEnabled` to true, now it works well for Linux kernel source code.  
Thank you very much!  This is very helpful for me.
