### ISSUE TITLE
search result moves cursor to line 0

### ISSUE THREAD

**Issue by scarf005** [gediminasz/ctags-companion#30]
https://user-images.githubusercontent.com/54838975/231213258-f79914a1-db54-4464-a67f-7a9d3affcf0d.mp4

extension correctly finds the file but does not move the cursor to definition.

excerpt from `.tags` file:
```
folding_stock	data/json/items/gunmod/stock.json	/^ *"id": "folding_stock"/
```

```sh
grep -nE '^ *"id": "folding_stock"' data/json/items/gunmod/stock.json
24:    "id": "folding_stock",
```
grep correctly finds line of definition.

**Comment by gediminasz** [comment]
@scarf005 I see your tags file is missing the line number. Could you try running ctags with this option: `--fields=+n`?

**Comment by scarf005** [comment]
i was using custom ctags generator and must've missed it.
after rewriting generator to write `line:{N}` at the end in [extended format](https://en.wikipedia.org/wiki/Ctags#Extended_Ctags), the extension works flawlessly.

```ctags
food	data/json/item_category.json	/"id": "food"/;"	line:46
```

thanks for the help!
