### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [gediminasz/ctags-companion#31]
Please add this useful extension to the [Open VSX Registry](https://open-vsx.org/?search=ctags).

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

A bit of explanation:
Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia, as well as browser versions like the one on GitPod. It would be nice to have this extension be directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

You could also use a [GitHub action](https://docs.github.com/en/actions) that allows publishing to Open VSX and the MS market place, [HaaLeo/publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension#readme) does this.

**Comment by GitMensch** [comment]
friendly ping after the holiday break :-)

**Comment by GitMensch** [comment]
Any updates on this?

**Comment by gediminasz** [comment]
Apologies, I was putting this off. I will bump this up in my todo list :)

**Comment by gediminasz** [comment]
The extension is now available on Open VSX: https://open-vsx.org/extension/gediminaszlatkus/ctags-companion Seems to work OK on VSCodium.

I will also make sure to publish all future releases there as well.

**Comment by GitMensch** [comment]
Thanks.
