### ISSUE TITLE
FR: add command to "lookup tag"

### ISSUE THREAD

**Issue by GitMensch** [gediminasz/ctags-companion#33]
This would allow to directly go to a tag, no matter where you currently are in the workspace.

**Comment by gediminasz** [comment]
This extension implements a provider for "Open symbol by name" (aka "Go to Symbol in Workspace") function: https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name

Is this something you are looking for?

**Comment by GitMensch** [comment]
Yes, that's totally what I've meant. It _is_ listed in the README but even after reading it I was not aware of this.

Would you mind adjusting the "Features" list to give a short note about what this feature means for a user and add a link as done above to "fix" this issue?

**Comment by gediminasz** [comment]
Updated the readme with links to official documentation.
