### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by kjh-miftek** [gediminasz/ctags-companion#42]
I have the following in my settings.json

{
    "ctags-companion.command": "ctags -R --fields=+nKz -f .vscode/.tags --langmap=SystemVerilog:+.v -R rtl /opt/uvm-1.2/src",
    "ctags-companion.readtagsEnabled": true,
}

In order to run it the docs say to run "Terminal > Run Task... > Ctags Companion: rebuild tags" but I have no task with that name

I do get an option in the menu for "Ctags Companion: reindex", but when I run it I get an error "Command 'ctags-companion.reindex' not found"

**Comment by gediminasz** [comment]
Hi,

When using the latest version of the extension, please try the following settings:

```
{
    "ctags-companion.command": "ctags -R --fields=+nKz --langmap=SystemVerilog:+.v -R rtl /opt/uvm-1.2/src",
}
```

Specifically:

* Remove `-f .vscode/.tags`
* Remove `"ctags-companion.readtagsEnabled": true,`

To find the task you may need to select "Show All Tasks":

![Screenshot 2023-10-17 at 22 44 41](https://github.com/gediminasz/ctags-companion/assets/699568/30de4da1-e02b-44c0-90e0-977a04ae1731)

![Screenshot 2023-10-17 at 22 45 48](https://github.com/gediminasz/ctags-companion/assets/699568/cd123adb-0974-4430-8cba-c60098c20bb9)

For convenience you may want to add the following setting:

```
"task.quickOpen.showAll": true
```

**Comment by kjh-miftek** [comment]
Perfect, thanks!
